const translate = key => {
  return texts[key] ? texts[key] : key;
};

export { translate };

// Temporary, wil be taken from DB with an API
const texts = {
  logOut: "LOG OUT",
  login: "LOG IN",
  unauthErr: "401 error: Unauthorized",
  menuFirstItem: "My profile",
  menuSecondItem: "Edit profile",
  menuThirdItem: "Manage listings",
  contactInfo: "Contact Info",
  location: "Location",
  about: "About you",
  name: "Last Name",
  firstName: "First Name",
  email: "E-mail",
  cellPhone: "Cell Phone",
  phone: "Phone",
  website: "Website",
  additionalInfo: "Additional Information",
  country: "Country",
  region: "Region",
  city: "City",
  cityArea: "City Area",
  address: "Address",
  zipCode: "Zip Code",
  updateProfile: "Update Profile",
  changePsd: "Change Password",
  newPsd: "New password",
  confirmPsd: "Confirm password",
  save: "Save",
  newPsdErrorMsg: "New password field is requied.",
  confirmPsdErrorMsg: "Confirm password field is requied.",
  updatePsdSuccessMsg: "Password successfully updated!",
  updateProfileSuccessMsg: "Profile successfully updated!",
  updateProfileErrorMsg: "Error: update profile failed.",
  close: "Close",
  bulkAction: "Bulk actions",
  addNew: "Add new",
  listings: "Listings",
  search: "Search",
  showFilter: "SHOW FILTER",
  hideFilter: "HIDE FILTER",
  delete: "Delete",
  id: "Anzeigen ID",
  title: "Anzeigentitel",
  adsLocation: "Standort",
  date: "Date",
  status: "Status",
  actions: "Actions",
  edit: "Edit",
  view: "View",
  activate: "Activate",
  deactivate: "Deactivate",
  archive: "Archive",
  unarchive: "Unarchive",
  category: "Category",
  premium: "Premium",
  active: "Active",
  block: "Block",
  spam: "Spam",
  chooseOption: "Choose an option",
  applyFilter: "APPLY FILTER",
  resetFilter: "RESET FILTER",
  confirmToDelete: "Are you sure you want to delete",
  confirmToDeleteList: "Are you sure you want to delete the selected ads?",
  yes: "Yes",
  editingAdsTitle: "Editing ads will be available soon!",
  noAdsMsg: "There are no Ads for filter requirements.",
  no: "No",
  emailRequired: "Email required",
  emailInvalid: "Email address is invalid",
  passwordRequired: "Password is required",
  passwordLength: "Password needs to be 9 characters or more",
  firstNameRequired: "First Name required",
  lastNameRequired: "Last Name required",
  passwordConfirmation: "Password is required",
  passwordMatch: "Passwords do not match",
  phoneNumberRequired: "Phone number is required",
  phoneNumberLength: "Phone number needs to be 6 characters or more",
  termsRequired: "Please Accept Terms and Conditions",
  policyRequired: "Please Accept Our Privacy Policy",
  userNameRequired: "Username required",
  createYourAccount: "Create Your Account",
  registerTitle: "REGISTER",
  registerContacts: "CONTACTS",
  registerAdress: "ADRESS",
  termsAndConditions: "Agree to <b>terms and conditions</b>",
  privacyPolicy: " Agree to <b>privacy policy of evodi.de.</b>",
  signUpbtn: "Sign Up",
  questionAccount: "Have an account?",
  linkSignIn: "Sign in",
  genderMale: "Male",
  genderFemale: "Female",
  genderTitle: "Gender",
  labelEmail: "Enter your email",
  labelUserName: "User name",
  labelPassword1: "Enter your password",
  labelPassword2: "Confirm your password",
  labelName: "Name",
  labelLastName: "Last name",
  address: "Str...",
  loginAccount: "Sign In",
  rememberMecheck: "Remember me",
  forgotPassword: "Forgot Password ?",
  loginBtn: "Log in",
  noAccount: "No Account ?",
  signUpLink: "Sign up",
  forgotPassword: "Forgot your password?",
  forgotPasswordBtn: "Send Email",
  backLoginLink: "Back to Login",
  EmailPasswordError: "Invalid Email or Password",
  EmailExists: "Email Already Exists",
  resetPassword: "Reset Password",
  reset: "Submit",
  successlink: "We Send You a Reset Email",
  EmailPasresetError: "Invalid Email",
  errorReset: "Reset Link has Expired",
  countryerror: "Select country please!",
  regionerror: "Select region please!",
  succesRegister: "We have received your request!",
  goLogin: "Go to login",
};
