export const types = {
  GET_COUNTRIES: "GET_COUNTRIES",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAIL: "GET_COUNTRIES_FAIL",

  GET_REGIONS: "GET_REGIONS",
  GET_REGIONS_SUCCESS: "GET_REGIONS_SUCCESS",
  GET_REGIONS_FAIL: "GET_REGIONS_FAIL",

  GET_CITIES: "GET_CITIES",
  GET_CITIES_SUCCESS: "GET_CITIES_SUCCESS",
  GET_CITIES_FAIL: "GET_CITIES_FAIL",

  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  SET_USER: "SET_USER",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAIL: "SET_USER_FAIL",

  GET_ADS: "GET_ADS",
  GET_ADS_SUCCESS: "GET_ADS_SUCCESS",
  GET_ADS_FAIL: "GET_ADS_FAIL",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",

  UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",
  UPDATE_USER_PASSWORD_SUCCESS: "UPDATE_USER_PASSWORD_SUCCESS",
  UPDATE_USER_PASSWORD_FAIL: "UPDATE_USER_PASSWORD_FAIL",

  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAIL: "UPDATE_USER_PROFILE_FAIL",

  POST_AD_TO_ARCHIVE: "POST_AD_TO_ARCHIVE",
  POST_AD_TO_ARCHIVE_SUCCESS: "POST_AD_TO_ARCHIVE_SUCCESS",
  POST_AD_TO_ARCHIVE_FAIL: "POST_AD_TO_ARCHIVE_FAIL",

  ACTIVATE_AD: "ACTIVATE_AD",
  ACTIVATE_AD_SUCCESS: "ACTIVATE_AD_SUCCESS",
  ACTIVATE_AD_FAIL: "ACTIVATE_AD_FAIL",

  DEACTIVATE_AD: "DEACTIVATE_AD",
  DEACTIVATE_AD_SUCCESS: "DEACTIVATE_AD_SUCCESS",
  DEACTIVATE_AD_FAIL: "DEACTIVATE_AD_FAIL",

  DELETE_AD: "DELETE_AD",
  DELETE_AD_SUCCESS: "DELETE_AD_SUCCESS",
  DELETE_AD_FAIL: "DELETE_AD_FAIL",

  LOG_IN_USER: "LOG_IN_USER",
  LOG_IN_USER_SUCCESS: "LOG_IN_USER_SUCCESS",
  LOG_IN_USER_FAIL: "LOG_IN_USER_FAIL",

  CLEAR_AUTHENTICATE: "CLEAR_AUTHENTICATE",
  LOG_OUT: "LOG_OUT",

  SEND_RESET_EMAIL: "SEND_RESET_EMAIL",
  SEND_RESET_EMAIL_SUCCESS: "SEND_RESET_EMAIL_SUCCESS",
  SEND_RESET_EMAIL_FAIL: "SEND_RESET_EMAIL_FAIL",

  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",
};
